minor fix, relocate activitySafeDialogActor.start because of market report
java.lang.RuntimeException: Unable to get provider org.digimead.digi.ctrl.s.main.ControlProvider: java.lang.IllegalArgumentException
at android.app.ActivityThread.installProvider(ActivityThread.java:4509)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:4281)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4237)
at android.app.ActivityThread.access$3000(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException
at scala.actors.threadpool.ThreadPoolExecutor.<init>(Unknown Source)
at scala.actors.scheduler.ResizableThreadPoolScheduler.makeNewPool(ResizableThreadPoolScheduler.scala:62)
at scala.actors.scheduler.ResizableThreadPoolScheduler.<init>(ResizableThreadPoolScheduler.scala:72)
at scala.actors.scheduler.ResizableThreadPoolScheduler.<init>(ResizableThreadPoolScheduler.scala:77)
at scala.actors.Scheduler$.makeNewScheduler(Scheduler.scala:28)
at scala.actors.scheduler.DelegatingScheduler$class.newActor(DelegatingScheduler.scala:63)
at scala.actors.Scheduler$.newActor(Scheduler.scala:21)
at scala.actors.Reactor$class.dostart(Reactor.scala:221)
at org.digimead.digi.ctrl.lib.base.AppComponent$$anon$2.scala$actors$Actor$$super$dostart(AppComponent.scala:95)
at scala.actors.Actor$class.dostart(Actor.scala:682)
at org.digimead.digi.ctrl.lib.base.AppComponent$$anon$2.dostart(AppComponent.scala:95)
at scala.actors.Reactor$class.start(Reactor.scala:230)
at org.digimead.digi.ctrl.lib.base.AppComponent$$anon$2.scala$actors$Actor$$super$start(AppComponent.scala:95)
at scala.actors.Actor$class.start(Actor.scala:686)
at org.digimead.digi.ctrl.lib.base.AppComponent$$anon$2.start(AppComponent.scala:95)
at org.digimead.digi.ctrl.lib.base.AppComponent.<init>(AppComponent.scala:141)
at org.digimead.digi.ctrl.lib.base.AppComponent$.initRoutine(AppComponent.scala:473)
at org.digimead.digi.ctrl.lib.base.AppComponent$.init(AppComponent.scala:451)
at org.digimead.digi.ctrl.lib.AnyBase$.init(AnyBase.scala:92)
at org.digimead.digi.ctrl.s.main.ControlProvider.onCreate(ControlProvider.scala:151)
at android.content.ContentProvider.attachInfo(ContentProvider.java:790)
at android.app.ActivityThread.installProvider(ActivityThread.java:4506)
... 12 more